name: dbt command (aws)
description: "---"

inputs:
  dbt_project_name:
    description: "dbt project name"
    required: false
    default: "sample_project"
  dbt_command:
    description: Command to be executed
    default: compile
    required: false

  client_id:
    description: "Service principal client id"
    required: true
  client_secret:
    description: "Service principal client secret"
    required: true

  host:
    description: "Databricks workspace host"
    required: true
  http_path:
    description: "Databricks SQL warehouse HTTP path"
    required: true
  catalog:
    description: "dbt target catalog"
    required: true
  schema:
    description: "dbt target schema"
    required: true

runs:
  using: 'composite'
  steps:

    - name: Prepare dbt profile
      shell: bash
      run: |
        mkdir -p .dbt/temporary

        cat > .dbt/temporary/profiles.yml <<EOF
        ${PROFILE_NAME}:
          target: cicd
          outputs:
            cicd:
              type: databricks
              method: http
              catalog: "{{ env_var('DBT_CATALOG') }}"
              schema: "{{ env_var('DBT_SCHEMA') }}"
              host: "{{ env_var('DATABRICKS_HOST') }}"
              http_path: "{{ env_var('DATABRICKS_HTTP_PATH') }}"
              auth_type: oauth
              client_id: "{{ env_var('DATABRICKS_CLIENT_ID') }}"
              client_secret: "{{ env_var('DATABRICKS_CLIENT_SECRET') }}"
        EOF
      env:
        PROFILE_NAME: ${{ inputs.dbt_project_name }}

    - name: dbt command
      shell: bash
      run: |
        uv run dbt ${{ inputs.dbt_command }} \
          --project-dir dbt/${{ inputs.dbt_project_name }} \
          --profiles-dir .dbt/temporary \
          --target cicd
      env:
        DATABRICKS_CLIENT_ID: ${{ inputs.client_id }}
        DATABRICKS_CLIENT_SECRET: ${{ inputs.client_secret }}

        DATABRICKS_HOST: ${{ inputs.host }}
        DATABRICKS_HTTP_PATH: ${{ inputs.http_path }}
        DBT_CATALOG: ${{ inputs.catalog }}
        DBT_SCHEMA: ${{ inputs.schema }}
