targets:
  dev:
    mode: development
    default: true
    presets:
      tags:
        environment: ${bundle.target}
    workspace:
      host: https://dbc-22d1cc79-2974.cloud.databricks.com/
    permissions:
      - user_name: ${workspace.current_user.userName}
        level: CAN_MANAGE
    variables:
      var_source_catalog: sample
      var_catalog: second
      var_schema: ${workspace.current_user.short_name}
      var_warehouse_id: 6915297f40611326
