name: DAB - deploy
description: "---"

inputs:
  environment:
    description: Databricks bundle target
    default: tst
  bundle_path:
    description: Path to the Databricks bundle directory
    default: bundles/sample_bundle
    required: false
  databricks_client_id:
    description: Service principal client id
    required: true
  databricks_client_secret:
    description: Service principal client secret
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure authentication
      uses: databricks/setup-cli@main

    - name: Databricks Deploy
      shell: bash
      working-directory: ${{ inputs.bundle_path }}
      run: |
        databricks auth describe
        databricks bundle deploy -t ${{ inputs.environment }}
      env:
        DATABRICKS_CLIENT_ID: ${{ inputs.databricks_client_id }}
        DATABRICKS_CLIENT_SECRET: ${{ inputs.databricks_client_secret }}
          # DATABRICKS_BUNDLE_ENV: prod
