name: "uv setup"
description: "Installs uv, Python and project dependencies"

runs:
  using: "composite"
  steps:

  # - name: Checkout repository
  #   uses: actions/checkout@v4

  - name: Install uv
    uses: astral-sh/setup-uv@v7

  - name: Set up Python
    shell: bash
    run: uv python install

  - name: Install dependencies
    shell: bash
    run: uv sync
