sample_project:
   target: cicd
   outputs:
    cicd:
      type: databricks
      method: http
      catalog: "{{ env_var('DBT_CATALOG') }}"
      schema: "{{ env_var('DBT_SCHEMA') }}"
      host: "{{ env_var('DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH') }}"
      auth_type: oauth
      client_id: "{{ env_var('DATABRICKS_CLIENT_ID') }}"
      client_secret: "{{ env_var('DATABRICKS_CLIENT_SECRET') }}"
